// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9MneeTM9Q4lhrmwBjx3LgJCzouXmxzCo',
    appId: '1:953243344899:web:302f5db42b1d172dd5ae36',
    messagingSenderId: '953243344899',
    projectId: 'attendance-management-19421',
    authDomain: 'attendance-management-19421.firebaseapp.com',
    storageBucket: 'attendance-management-19421.appspot.com',
    measurementId: 'G-ENVB0HM171',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqtU1QdZY8R-O-LsLjLyRScDhrrJDPXwE',
    appId: '1:953243344899:android:47b653dc63947282d5ae36',
    messagingSenderId: '953243344899',
    projectId: 'attendance-management-19421',
    storageBucket: 'attendance-management-19421.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjcpCf9sIajxpnGb-BhS6gpVG7vGWlS4I',
    appId: '1:953243344899:ios:71e24f598dbf2000d5ae36',
    messagingSenderId: '953243344899',
    projectId: 'attendance-management-19421',
    storageBucket: 'attendance-management-19421.appspot.com',
    iosClientId: '953243344899-0hskra84psrfaggcjh3akb3pdftc7jqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.timetableManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjcpCf9sIajxpnGb-BhS6gpVG7vGWlS4I',
    appId: '1:953243344899:ios:71e24f598dbf2000d5ae36',
    messagingSenderId: '953243344899',
    projectId: 'attendance-management-19421',
    storageBucket: 'attendance-management-19421.appspot.com',
    iosClientId: '953243344899-0hskra84psrfaggcjh3akb3pdftc7jqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.timetableManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9MneeTM9Q4lhrmwBjx3LgJCzouXmxzCo',
    appId: '1:953243344899:web:24c0f6bf5ba3a3bfd5ae36',
    messagingSenderId: '953243344899',
    projectId: 'attendance-management-19421',
    authDomain: 'attendance-management-19421.firebaseapp.com',
    storageBucket: 'attendance-management-19421.appspot.com',
    measurementId: 'G-6KTXTXQ2SN',
  );
}
